In [ ]:
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
# URL halaman web yang akan diakses
url = 'https://id.wikipedia.org/wiki/Daftar_film_Indonesia_tahun_2024'

# Membuat permintaan HTTP dengan menambahkan header 'User-Agent'
manipulation = Request(url, headers={'User-Agent':'Mozila/5.0'})

# Membuka URL dan mengambil konten HTML Halaman
htmml_text = urlopen(manipulation)

# Memproses HTML 'html.parser' menggugunakan dengan BeautifulSoup untuk mempermudah analisis
soup = BeautifulSoup(htmml_text, 'html.parser')

In [ ]:
# Mencari tabel pertama dengan class 'wikitable'
tabel = soup.findAll('table',{'class':'wikitable'})[0]

# Mencari tabel pertama dengan class 'wikitable'
baris = tabel.findAll('tr')

In [ ]:
# Looping melalui setiap baris dalam tabel
for row in baris:
    # Untuk setiap baris, mencari semua elemen header (<th>) atau data (<td>)
    for cell in row.findAll(['th', 'td']):
        # Mengambil teks dari setiap sel tabel
        cell.get_text()

In [ ]:
# Membuat list kosong untuk menyimpan hasil
hasil = []

# Looping melalui setiap baris dalam tabel
for row in baris:
    # Membuat list kosong untuk menyimpan data tiap baris
    info = []

    # Untuk setiap baris, cari semua sel (baik header <th> atau data <td>)
    for cell in row.findAll(['th', 'td']):
        # Ambil teks dari sel dan hapus spasi di awal/akhir
        info.append(cell.get_text().strip())

    # Tambahkan data baris yang sudah diproses ke dalam hasil
    hasil.append(info)

In [ ]:
data = pd.DataFrame(hasil)
data

            0                                1                  2          3
0   Peringkat                            Judul           Produksi   Penonton
1           1                        Agak Laen          Imajinari  9.125.188
2           2             Vina: Sebelum 7 Hari        Dee Company  5.815.492
3           3            Kang Mak from Pee Mak    Falcon Pictures  4.860.034
4           4                 Ipar adalah Maut        MD Pictures  4.775.315
5           5        Badarawuhi di Desa Penari        MD Pictures  4.015.120
6           6                      Siksa Kubur         Rapi Films  4.000.826
7           7                     Sekawan Limo         Starvision  2.508.438
8           8                  Home Sweet Loan  Visinema Pictures  1.700.000
9           9                        Lembayung       MNC Pictures  1.656.149
10         10                  Pemandi Jenazah         VMS Studio  1.645.513
11         11                           Sumala   Hitmaker Studios  1.327.978
12         12  Ancika: Dia yang Bersamaku 1995        MD Pictures  1.318.272
13         13                      Kuasa Gelap   Paragon Pictures  1.314.942
14         14                            Laura        MD Pictures  1.268.765
15         15         The Architecture of Love         Starvision  1.003.999
16         16                  Kereta Berdarah       MVP Pictures  1.000.027
17         17  Bolehkah Sekali Saja Kumenangis  Sinemaku Pictures  1.000.000

In [ ]:
# Mengambil baris pertama sebagai header
header = data.iloc[0]

# Menghapus baris pertama yang sudah dijadikan header
data = data[1:]

# Menetapkan baris pertama sebagai nama kolom
data.columns = header

# Mengatur ulang index tanpa inplace
data = data.reset_index(drop=True)

In [ ]:
data.head()

0 Peringkat                      Judul         Produksi   Penonton
0         1                  Agak Laen        Imajinari  9.125.188
1         2       Vina: Sebelum 7 Hari      Dee Company  5.815.492
2         3      Kang Mak from Pee Mak  Falcon Pictures  4.860.034
3         4           Ipar adalah Maut      MD Pictures  4.775.315
4         5  Badarawuhi di Desa Penari      MD Pictures  4.015.120

In [ ]:
data['Produksi'].value_counts()

Produksi
MD Pictures          4
Starvision           2
Imajinari            1
Dee Company          1
Falcon Pictures      1
Rapi Films           1
Visinema Pictures    1
MNC Pictures         1
VMS Studio           1
Hitmaker Studios     1
Paragon Pictures     1
MVP Pictures         1
Sinemaku Pictures    1
Name: count, dtype: int64

In [ ]:
data['Produksi'].unique()

array(['Imajinari', 'Dee Company', 'Falcon Pictures', 'MD Pictures',
       'Rapi Films', 'Starvision', 'Visinema Pictures', 'MNC Pictures',
       'VMS Studio', 'Hitmaker Studios', 'Paragon Pictures',
       'MVP Pictures', 'Sinemaku Pictures'], dtype=object)